### ISSUE TITLE
load test -vs- unit test

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#10]
I would like very much to use this app to run unit tests, but am not sure on a complete solution

I would like to be able to create a chain/chain of topics to publish and expected payloads to receive in reply 

I know that mqtt doesn't have request-reply natively but in my own work with mqtt I have created a promise wrapper that publishes on a topic, after subscribing on that same topic with a '/reply' suffix -- then the payload from the reply is return on the promise resolution 

```
	// reply is _always_ the topicRequest with /reply suffix
	requestReply(topicRequest, payload, rr_qos = 0) {
		const topicReply = `${topicRequest}/reply`;
		return new Promise((resolve, reject) => {
			this.subscribe(topicReply,{ qos: rr_qos }, (payload) => {
				this.unsubscribe(topicReply, (err) => {
					if (err) {
						reject({ msg: 'unsubscribe error, '+err, payload: payload });
					}
				});
				resolve(payload);
			}, (err) => {
				if (err) {
					reject({ msg: 'subscribe error, '+err, payload: payload });
				} else {
					this.publish(topicRequest, payload, { qos: rr_qos });
				}
			});
		});
	}
```

It would be fabulous to see something like this as an future enhancement

**Comment by workswithweb** [comment]
Can you provide more details on this idea? We are working on similar project [virtual-device](https://github.com/workswithweb/virtual-device) creating chain/chain supporting multiple protocols (MQTT,HTTP,Web sockets etc). Response can be chained and used by different protocols. (like getting auth token using HTTP request and use it with next HTTP request or MQTT client id). 

please provide more details so that we can evaluate on this before adding to this app.

We are still in design phase of virtual-device project.

**Comment by ajoslin103** [comment]
looking forward to virtual-device -- will test anytime !!

I like the sound of it much better than this request-reply just in mqtt !!
