### ISSUE TITLE
multiple window support should be easier to find

### ISSUE THREAD

**Issue by ajoslin103** [workswithweb/MQTTBox#12]
feel lucky that I managed to figure out how to open multiple windows - did I miss it in the docs ?

**Comment by workswithweb** [comment]
You cannot open multiple instances of MQTTBox app. We had this feature before but has been deprecated .

We found that when users open multiple instances of app, many prefer to auto connect clients. In such cases, since clientId is same across app instances, connection to MQTT broker fails. It would be hard for users to know why connection was failing.

@ajoslin103 If you are mentioning something else, please provide more details.

**Comment by ajoslin103** [comment]
ok

**Comment by damogongzi** [comment]
I really hope you have the multiple windows feature. It is more easy to debug (sender, receiver). Right now I have to switch back and forth.
