### ISSUE TITLE
Running from tar.gz file not working

### ISSUE THREAD

**Issue by lixit** [workswithweb/MQTTBox#40]
According Installing on Linux Doc
I am using Arch Linux

./MQTTBox 
Segmentation fault (core dumped)

**Comment by heldermartins-tdesk** [comment]
To bring more detail to this After installing gtk2 and gconf I get the following error:

```
./MQTTBox 

(MQTTBox:56384): Pango-ERROR **: 17:30:38.263: Harfbuzz version too old (1.2.7)

[1]    56384 trace trap (core dumped)  ./MQTTBox

```

The version installed on the system is not the one mentioned in the error message. So it must be using some embedded version that I do not find the location (but using the system pango, which is a bit inconsistent). Is there any way to workaround this?

**Comment by Alexand3r** [comment]
+1 On Manjaro 18.1.3 
```
$ ./MQTTBox 

(MQTTBox:1895): Pango-ERROR **: 14:40:07.849: Harfbuzz version too old (1.2.7)

Trace/breakpoint trap (core dumped)
$
```

**Comment by espaciosdigitales** [comment]
+1 On Solus 4.1

> ~/MQTTBox-0.2.1 $ ./MQTTBox 

> (MQTTBox:36908): Pango-ERROR **: 11:12:53.003: Harfbuzz version too old (1.2.7)

> Trace/Breakpoint ausgelöst

**Comment by sathyavikram** [comment]
I have not been updating this tool or repo for long time.
I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.

**Comment by espaciosdigitales** [comment]
I think is a very good tool, it helps us in IoT HW development. Would be fantastic to have it working in the future.
Thanks!

**Comment by ajnashukkoor** [comment]
MQTTBox 
_Gtk-Message: 11:12:28.955: Failed to load module "canberra-gtk-module"

(MQTTBox:8087): Pango-ERROR **: 11:12:29.956: Harfbuzz version too old (1.2.7)

Trace/breakpoint trap (core dumped)_

facing this error, Kindly help.

Thank you

**Comment by Alexand3r** [comment]
> I have not been updating this tool or repo for long time.
> I had plan of rewriting this app but not sure if this tool is helping many devs worth my time. Will see if I get more feedback, I would like to re-architecture this app.

@sathyavikram If you have abandoned this repo at least let the people know that you have done that, either by editing the README and writing a couple of lines that the tool is deprecated/unmaintained or just add this line at the top of the README....

```
[![No Maintenance In|tended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
```

It will add this badge:
 [![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
http://unmaintained.tech/

Also closing opened issues just because the tool is unmaintained is counter productive, it will result in people opening more issues and in most cases they might be duplicates, if they really annoy you, just unsubscribe from the repo so you won't get notifications anymore...

**Comment by kuchaguangjie** [comment]
Yeah, the project is dead. Forget about it.
